# 빌드 설정
[build]
  command = "npm run build"
  publish = ".next"

# Netlify Next.js 플러그인 사용
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Next.js 정적 파일을 위한 리다이렉트
[[redirects]]
  from = "/_next/static/*"
  to = "/static/:splat"
  status = 200

# API 경로를 위한 리다이렉트
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nextjs-api/:splat"
  status = 200

# SPA 폴백 - 클라이언트 사이드 라우팅을 위함
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs-server"
  status = 200
  force = false
