# 빌드 설정
[build]
  command = "npm ci --prefer-offline --no-audit && npm run build"
  publish = ".next"
  
# 환경 변수 설정
[build.environment]
  NODE_VERSION = "18.19.0"
  NPM_VERSION = "10"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"
  NPM_FLAGS = "--prefer-offline --no-audit --legacy-peer-deps"
  NETLIFY_NEXT_PLUGIN_SKIP = "false"

# Netlify Next.js 플러그인 사용
[[plugins]]
  package = "@netlify/plugin-nextjs"

# 헤더 설정 - 보안 및 캐싱
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "public, max-age=0, must-revalidate"

# Next.js 정적 파일을 위한 리다이렉트
[[redirects]]
  from = "/_next/static/*"
  to = "/static/:splat"
  status = 200

# API 경로를 위한 리다이렉트
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nextjs-api/:splat"
  status = 200

# 카테고리 페이지 리다이렉트 (404 방지)
[[redirects]]
  from = "/category/*"
  to = "/.netlify/functions/nextjs-server"
  status = 200

# SPA 폴백 - 클라이언트 사이드 라우팅을 위함
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs-server"
  status = 200
  force = false
